### ISSUE TITLE
The whole tree is always parsed

### ISSUE THREAD

**Issue by tischi** [saalfeldlab/n5-universe#21]
In the function https://github.com/saalfeldlab/n5-universe/blob/b68a997a98abe9d88ca13c688cbbb6a826a0844b/src/main/java/org/janelia/saalfeldlab/n5/universe/N5MetadataUtils.java#L109 the argument `parseWholeTree` is ignored and the whole tree is always parsed.

**Comment by bogovicj** [comment]
https://github.com/saalfeldlab/n5-universe/commit/75a5866577c6f020b2fe2648f991fad336095bcb

**Comment by bogovicj** [comment]
closing since this is now released
