### ISSUE TITLE
Just use the Anonymous Credentials if they are given

### ISSUE THREAD

**Issue by tischi** [saalfeldlab/n5-universe#23]
Currently, I think using

```
N5Factory n5Factory = new N5Factory();
n5Factory.s3UseCredentials( new AnonymousAWSCredentials() );
```

would still result the code to [execute these checks](https://github.com/saalfeldlab/n5-aws-s3/blob/52ad9c59b3a22731c4250f78edc2d8f8b360b329/src/main/java/org/janelia/saalfeldlab/n5/s3/AmazonS3Utils.java#L185-L194), which can be slow.

I think if a user _explicitly_ provides the `AnonymousAWSCredentials` (as in my example above), one could skip this test to save time and assume that it should work (and if it does not work it is the fault of the user).

What do you think @bogovicj ?

**Comment by bogovicj** [comment]
Good idea, thanks!

**Comment by bogovicj** [comment]
@tischi I did what you suggested here https://github.com/saalfeldlab/n5-aws-s3/commit/8e708371ef5c5958268f330164821f1bb688ebaa
and it behaves as I'd expect it to.

**Comment by tischi** [comment]
Thanks @bogovicj!

Did you by chance already try how fast such code would execute now?

```
        String uri = "https://s3.embl.de/i2k-2020/platy-raw.ome.zarr";
        long start = System.currentTimeMillis();
        N5URI n5URI = new N5URI( uri );
        String containerPath = n5URI.getContainerPath();
        N5Factory n5Factory = new N5Factory();
        n5Factory.s3UseCredentials( new AnonymousAWSCredentials() );
        N5Reader n5 = n5Factory.openReader( containerPath );
        System.out.println( "Opened reader of " + uri + " in [ms]: " + ( System.currentTimeMillis() - start ) );
```

If not, let me know, then I could build your branch locally and try myself.

**Comment by bogovicj** [comment]
It's a bit faster, but that check wasn't the slowest thing.

To make the `N5Reader`, it takes 3.8-4.1s using `n5Factory.s3UseCredentials( new AnonymousAWSCredentials() );` and skipping the check, and `4.0-4.5s doing the check. 

You should also try yourself because iirc, your startup times were much slower.  I don't know why - I expect its outside the control of n5.

**Comment by bogovicj** [comment]
done: https://github.com/saalfeldlab/n5-aws-s3/commit/f2901bd6886cb8a756713407097720c0bc9dfb12
